name: Deploy Web Application

on:
  push:
    branches:
      - master
jobs:
  build-and-push:
    environment: EC2-Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
# login to docker hub and create and push docker image
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend-app:latest ./Stock
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend-app:latest
      
      - name: Build and Push Backend Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend-app:latest ./Data_Api
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend-app:latest
# create Ec2 instance with terraform
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        working-directory: terraform
        run: terraform init
      - name: validate Terraform
        working-directory: terraform
        run: terraform validate
      - name: Plan Terraform
        working-directory: terraform
        run: terraform plan
      - name: Apply Terraform
        working-directory: terraform
        run: terraform apply -auto-approve
# connect ec2 and run the docker app image 
      - name: Get EC2 Public IP  
        id: ip
        working-directory: terraform 
        run: echo "EC2_IP=$(terraform output -raw instance_ip)" >>$GITHUB_ENV
      - name: SSH and Deploy
        env:
          EC2_USER: ubuntu
          EC2_KEY: ${{ secrets.EC2_SSH_KEY}}
        run: |
           echo "$EC2_KEY" > ec2_key.pem
           chmod 600 ec2_key.pem
           ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${EC2_USER}@${{ env.EC2_IP }} << EOF
           cd my-web-app
           git pull origin master
           docker-compose up -d --build
           

          
            
        
  
  
